import { MONITOR_BENCHMARK_PREFIX } from "./otlp-conventions.js";
import type {
  ComparisonEntry,
  ComparisonResult,
  FormatComparisonMarkdownOptions,
} from "./types.js";

const DEFAULT_OPTIONS: Required<
  Pick<
    FormatComparisonMarkdownOptions,
    "currentLabel" | "baselineLabel" | "maxRegressions" | "includeDetails" | "footerHref"
  >
> = {
  currentLabel: "Current",
  baselineLabel: "Baseline",
  maxRegressions: 10,
  includeDetails: true,
  footerHref: "https://github.com/strawgate/benchkit",
};

function isMonitorEntry(entry: ComparisonEntry): boolean {
  return entry.benchmark.startsWith(MONITOR_BENCHMARK_PREFIX);
}

function sortEntries(entries: ComparisonEntry[]): ComparisonEntry[] {
  return [...entries].sort((a, b) => {
    if (a.benchmark !== b.benchmark) return a.benchmark.localeCompare(b.benchmark);
    return a.metric.localeCompare(b.metric);
  });
}

function formatNumber(value: number): string {
  if (Math.abs(value) >= 1000 || Number.isInteger(value)) {
    return value.toLocaleString("en-US", { maximumFractionDigits: 0 });
  }

  return value.toLocaleString("en-US", { maximumFractionDigits: 2 });
}

function formatValue(value: number, unit?: string): string {
  return unit ? `${formatNumber(value)} ${unit}` : formatNumber(value);
}

function formatPercent(value: number): string {
  return `${value > 0 ? "+" : ""}${value.toFixed(2)}%`;
}

function directionArrow(entry: ComparisonEntry): string {
  if (entry.status === "stable") return "→";
  if (entry.direction === "smaller_is_better") {
    return entry.status === "regressed" ? "↑" : "↓";
  }
  return entry.status === "regressed" ? "↓" : "↑";
}

function statusLabel(entry: ComparisonEntry): string {
  return `${entry.status} ${directionArrow(entry)}`;
}

function formatRef(ref: string): string {
  const prMatch = /^refs\/pull\/(\d+)\/merge$/.exec(ref);
  if (prMatch) return `PR #${prMatch[1]}`;
  if (ref.startsWith("refs/heads/")) return ref.replace("refs/heads/", "");
  if (ref.startsWith("refs/tags/")) return `tag ${ref.replace("refs/tags/", "")}`;
  return ref;
}

function formatHeader(options: FormatComparisonMarkdownOptions): string[] {
  const lines: string[] = [];
  lines.push(`## ${options.title ?? "Benchmark Comparison"}`);
  if (options.currentCommit || options.currentRef) {
    const parts = [
      options.currentCommit ? `commit \`${options.currentCommit.slice(0, 8)}\`` : "",
      options.currentRef ? `ref \`${formatRef(options.currentRef)}\`` : "",
    ].filter(Boolean);
    lines.push(`Comparing results for ${parts.join(" on ")}.`);
  }
  return lines;
}

function escapeMarkdownCell(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/`/g, "\\`");
}

function formatTable(entries: ComparisonEntry[], options: Required<Pick<FormatComparisonMarkdownOptions, "currentLabel" | "baselineLabel">>): string[] {
  const lines = [
    `| Benchmark | Metric | ${options.baselineLabel} | ${options.currentLabel} | Δ% | Status |`,
    "| --- | --- | --- | --- | --- | --- |",
  ];

  for (const entry of sortEntries(entries)) {
    lines.push(
      `| \`${escapeMarkdownCell(entry.benchmark)}\` | \`${escapeMarkdownCell(entry.metric)}\` | ${formatValue(entry.baseline, entry.unit)} | ${formatValue(entry.current, entry.unit)} | ${formatPercent(entry.percentChange)} | ${statusLabel(entry)} |`,
    );
  }

  return lines;
}

function groupByMetric(entries: ComparisonEntry[]): Map<string, ComparisonEntry[]> {
  const grouped = new Map<string, ComparisonEntry[]>();
  for (const entry of entries) {
    const key = entry.metric;
    const existing = grouped.get(key);
    if (existing) existing.push(entry);
    else grouped.set(key, [entry]);
  }
  return new Map([...grouped.entries()].sort((a, b) => a[0].localeCompare(b[0])));
}

export function formatComparisonMarkdown(
  result: ComparisonResult,
  options: FormatComparisonMarkdownOptions = {},
): string {
  const resolved = { ...DEFAULT_OPTIONS, ...options };
  const lines: string[] = [];

  lines.push(...formatHeader(options));
  lines.push("");

  if (result.entries.length === 0) {
    if ((result.baselineRunCount ?? 0) > 0) {
      lines.push(
        `No benchmark names matched between the current run and ${result.baselineRunCount} baseline run(s). ` +
        "Verify your benchmark names haven't changed, or that the correct result file is being passed.",
      );
    } else {
      lines.push("No comparable baseline data found.");
    }
    lines.push("");
    lines.push(`Generated by [benchkit](${resolved.footerHref}).`);
    return lines.join("\n");
  }

  const benchmarkEntries = result.entries.filter((entry) => !isMonitorEntry(entry));
  const monitorEntries = result.entries.filter((entry) => isMonitorEntry(entry));
  const regressions = sortEntries(result.entries.filter((entry) => entry.status === "regressed"));

  if (regressions.length > 0) {
    lines.push("### Regressions");
    lines.push("");
    lines.push(...formatTable(regressions.slice(0, resolved.maxRegressions), resolved));
    if (regressions.length > resolved.maxRegressions) {
      lines.push("");
      lines.push(`Showing ${resolved.maxRegressions} of ${regressions.length} regressions.`);
    }
    lines.push("");
  } else {
    lines.push("No regressions detected.");
    lines.push("");
  }

  if (benchmarkEntries.length > 0) {
    lines.push("### Benchmark Metrics");
    lines.push("");
    lines.push(...formatTable(benchmarkEntries, resolved));
    lines.push("");
  }

  if (monitorEntries.length > 0) {
    lines.push("### Monitor Metrics");
    lines.push("");
    lines.push(...formatTable(monitorEntries, resolved));
    lines.push("");
  }

  if (resolved.includeDetails) {
    const grouped = groupByMetric(result.entries);
    lines.push("<details>");
    lines.push("<summary>Per-metric detail</summary>");
    lines.push("");
    for (const [metric, entries] of grouped.entries()) {
      lines.push(`#### \`${metric}\``);
      lines.push("");
      lines.push(...formatTable(entries, resolved));
      lines.push("");
    }
    lines.push("</details>");
    lines.push("");
  }

  lines.push(`Generated by [benchkit](${resolved.footerHref}).`);
  return lines.join("\n");
}
